source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'BNRCoreDataStackConvenienceUpdates_Tests', :exclusive => true do
  pod 'BNRCoreDataStackConvenienceUpdates', :path => '../'
end
